on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version-file: "go.mod"
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: go test ./...
